name: flutter_shop
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  sizer: ^2.0.15
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
