name: flutter_shop
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  sizer: ^2.0.15
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  http: ^1.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env.local
    - assets/text.png
